USE DW
GO
SET NOCOUNT ON

DECLARE @TABELA VARCHAR(100) = 'TF_ACOMP_PRODUTOR'
DECLARE @ID_COLUNA INT
DECLARE @COLUNA VARCHAR(100)
DECLARE @TIPO VARCHAR(10)
DECLARE @FILTRO_NULO VARCHAR(MAX)
DECLARE @FILTRO_ZERO VARCHAR(MAX)
DECLARE @SQL VARCHAR(MAX)

DECLARE @TB_TABELAS TABLE(TABELA VARCHAR(100))
DECLARE @TB_COLUNAS TABLE(ID INT, COLUNA VARCHAR(100), TIPO VARCHAR(10))
DECLARE @TB_RESULT TABLE(
						ID INT,
						TABELA VARCHAR(100), 
						DESCRICAO VARCHAR(100), 
						QTDE_LINHAS INT, 
						QTD_NULOS INT, 
						QTD_ZEROS INT,
						QTD_VAZIOS INT
						)

DECLARE @TB_SQLs TABLE(CMD_SQL VARCHAR(MAX))
DECLARE @CAMPOS VARCHAR(MAX) = '',
		@FILTROS VARCHAR(MAX) = ''
		
INSERT INTO @TB_TABELAS
	SELECT name
	FROM sys.tables T
	WHERE T.name IN(@TABELA)

WHILE ((SELECT COUNT(1) FROM @TB_TABELAS) > 0)
BEGIN
	SELECT TOP 1 @TABELA = TABELA FROM @TB_TABELAS
	--INICIO LOOP 1-------------------------------
	DELETE FROM @TB_COLUNAS
	INSERT INTO @TB_COLUNAS
		SELECT C.column_id, C.name, T.name
		FROM sys.columns C 
		JOIN SYS.types T 
			ON T.system_type_id = C.system_type_id
		JOIN sys.tables TB
			ON TB.object_id = C.object_id
		WHERE 1=1
			AND TB.name = @TABELA
		
	--SELECT * FROM @TB_COLUNAS
	
	SET @CAMPOS = ''
	SET @FILTROS = ''
	WHILE ((SELECT COUNT(1) FROM @TB_COLUNAS) > 0)
	BEGIN
		SELECT TOP 1 @ID_COLUNA = ID, @COLUNA = COLUNA, @TIPO = TIPO FROM @TB_COLUNAS ORDER BY COLUNA
		
		--INICIO LOOP 2-------------------------------------------------------------
		SET @FILTRO_NULO = ''
		SET @FILTRO_ZERO = ''
		IF (@TIPO IN('bigint','int','numeric'))
		BEGIN
			SET @FILTRO_NULO = @FILTRO_NULO + 'SUM(CASE WHEN ('+@COLUNA+' IS NULL) THEN 1 ELSE 0 END) AS QTD_NULOS'
			SET @FILTRO_ZERO = @FILTRO_ZERO + ',SUM(CASE WHEN ('+@COLUNA+' = 0) THEN 1 ELSE 0 END) AS QTD_ZEROS'
			SET @FILTRO_ZERO = @FILTRO_ZERO + ',SUM(0) AS QTD_VAZIOS'
			SET @CAMPOS = @CAMPOS + ',case when ISNULL('+@COLUNA+',0) = 0 then 1 else 0 end f_'+@COLUNA
		END
		ELSE IF(@TIPO IN('date','datetime'))
		BEGIN
			SET @FILTRO_NULO = @FILTRO_NULO + 'SUM(CASE WHEN ('+@COLUNA+' IS NULL) THEN 1 ELSE 0 END) AS QTD_NULOS'
			SET @FILTRO_ZERO = @FILTRO_ZERO + ',SUM(CASE WHEN (RTRIM(LTRIM('+@COLUNA+')) = ''0'') THEN 1 ELSE 0 END) AS QTD_ZEROS'
			SET @FILTRO_ZERO = @FILTRO_ZERO + ',SUM(0) AS QTD_VAZIOS'
			SET @CAMPOS = @CAMPOS + ',case when '+@COLUNA+' is null then 1 else 0 end f_'+@COLUNA
		END
		ELSE
		BEGIN
			SET @FILTRO_NULO = @FILTRO_NULO + 'SUM(0) AS QTD_NULOS'
			SET @FILTRO_ZERO = @FILTRO_ZERO + ',SUM(0) AS QTD_ZEROS'
			SET @FILTRO_ZERO = @FILTRO_ZERO + ',SUM(CASE WHEN (RTRIM(LTRIM(ISNULL('+@COLUNA+',''''))) = '''') THEN 1 ELSE 0 END) AS QTD_ZEROS'
			SET @CAMPOS = @CAMPOS + ',case when RTRIM(ISNULL('+@COLUNA+','''')) = '''' then 1 else 0 end f_'+@COLUNA
		END
		
		SET @FILTROS = @FILTROS + ' OR f_'+@COLUNA+' = 1'
		
		SET @SQL = 
		'SELECT 
			 '+CAST(@ID_COLUNA AS VARCHAR)+'  AS ID
			,'''+@TABELA+''' AS TABELA
			,'''+@COLUNA+''' AS DESCRICAO
			,COUNT(1) AS QTDE_LINHAS
			,'+@FILTRO_NULO+@FILTRO_ZERO+'
		FROM [dbo].['+@TABELA+']'
		
		INSERT INTO @TB_RESULT EXEC(@SQL)
		
		--FIM LOOP 2----------------------------------------------------------------
		DELETE FROM @TB_COLUNAS WHERE COLUNA = @COLUNA
	END
	
	INSERT INTO @TB_SQLs (CMD_SQL)
	VALUES
		('select '''+@TABELA+''' AS TABELA, * from (SELECT * '+@CAMPOS+' FROM '+@TABELA+')x where (0=1 '+@FILTROS+') ORDER BY 1')
	
	--FIM LOOP 1----------------------------------
	DELETE FROM @TB_TABELAS WHERE TABELA = @TABELA
END

SELECT * FROM @TB_RESULT ORDER BY TABELA, ID, DESCRICAO
GO
